### ISSUE TITLE
Missing rsync install for test user in Dockerfile

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/heiko#12]
When `heiko` is run with the `test` user using the docker-networks.py file, logs show an error saying that `rsync` is not found. 

This should be pretty straightforward to fix:
```Dockerfile
RUN echo yabe | sudo -S apt-get install rsync -y
```

**Comment by Samyak2** [comment]
Looks like the Dockerfile could use some other improvements on the apt install side too. I'll look at this. Thank you for reporting!

**Comment by Samyak2** [comment]
F, I just noticed that you did it in #11

**Comment by MadhavJivrajani** [comment]
Oh, I had, but I reverted it because it wasn't part of the PR
