### ISSUE TITLE
Logs follow argument takes too much CPU

### ISSUE THREAD

**Issue by Samyak2** [pesos/heiko#7]
**Describe the bug**

When `heiko logs` is used with the follow (`-f`) parameter, it utilizes 100% of a CPU thread.

**To Reproduce**
1. Set up a heiko app and start it with `heiko start --name something`
2. Check logs with `heiko logs -f --name something`
3. Open your favourite system monitor tool (example: `htop`, `top`, `bpytop`)
4. Notice heiko going brr

**Expected behavior**
Following the logs shouldn't take so much CPU, things like `tail -f` do it without much CPU usage.

**Desktop (please complete the following information):**
 - OS: Fedora 33 KDE
 - `heiko` Version: master
 - Python version: 3.9

Also noticed on a Raspberry Pi 4

**Additional context**

The function which is responsible for following logs is here:

https://github.com/pesos/heiko/blob/29c726f1b64311f229feed9f237fc0bc0c57e728/heiko/cli.py#L122-L143

Which is used here:

https://github.com/pesos/heiko/blob/29c726f1b64311f229feed9f237fc0bc0c57e728/heiko/cli.py#L213-L216

**Comment by MadhavJivrajani** [comment]
Hey, [this](http://amoffat.github.io/sh/tutorials/real_time_output.html?highlight=tail#tailing-a-real-time-log-file) could be helpful, although introduces external dependency

**Comment by Samyak2** [comment]
> Hey, [this](http://amoffat.github.io/sh/tutorials/real_time_output.html?highlight=tail#tailing-a-real-time-log-file) could be helpful, although introduces external dependency

Thanks for the link, that syntax is quite clean! Though the same can be achieved using [subprocess](https://stackoverflow.com/a/12523371/11199009). Since we're already using subprocess (in `heiko/utils/sync.py`), we could use the same here.

**Comment by MadhavJivrajani** [comment]
Hey, can I try this?

**Comment by Samyak2** [comment]
Sure!
